FROM node:20-alpine AS deps
WORKDIR /app
COPY package.json ./
COPY tsconfig.base.json ./
COPY packages ./packages
COPY services ./services
RUN npm install

FROM deps AS build
ARG SERVICE_PATH
RUN npm --workspace ${SERVICE_PATH} run build

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
ARG SERVICE_PATH
ENV SERVICE_PATH=${SERVICE_PATH}
COPY --from=deps /app/node_modules ./node_modules
COPY --from=deps /app/package.json ./package.json
COPY --from=deps /app/services ./services
COPY --from=build /app/${SERVICE_PATH}/dist ./${SERVICE_PATH}/dist
CMD ["sh", "-c", "node ${SERVICE_PATH}/dist/main.js"]
