FROM node:20-alpine AS deps
WORKDIR /app
COPY package.json ./
COPY tsconfig.base.json ./
COPY packages ./packages
COPY apps ./apps
RUN npm install

FROM deps AS build
ARG APP_PATH
RUN npm --workspace ${APP_PATH} run build

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
ARG APP_PATH
ENV APP_PATH=${APP_PATH}
COPY --from=deps /app/node_modules ./node_modules
COPY --from=deps /app/package.json ./package.json
COPY --from=deps /app/apps ./apps
COPY --from=build /app/${APP_PATH}/.next ./${APP_PATH}/.next
CMD ["sh", "-c", "npm --workspace ${APP_PATH} run start"]
